### ISSUE TITLE
Problem when loading captcha via http

### ISSUE THREAD

**Issue by nickcname13241** [AdminAnticaptcha/anticaptcha-python#7]
Here is a code:

```
from anticaptchaofficial.imagecaptcha import *

solver = imagecaptcha()
solver.set_verbose(1)
solver.set_key("KEY")

captcha_text = solver.solve_and_return_solution('https://raw.githubusercontent.com/AdminAnticaptcha/anticaptcha-python/master/captcha.jpeg')
if captcha_text != 0:
    print("captcha text "+captcha_text)
else:
    print("task finished with error "+solver.error_code)
```
Here is a error:

```
Traceback (most recent call last):
  File "/Users/test/Desktop/New Folder With Items 2/test 3.py", line 37, in <module>
    captcha_text = solver.solve_and_return_solution('https://raw.githubusercontent.com/AdminAnticaptcha/anticaptcha-python/master/captcha.jpeg')
  File "/usr/local/lib/python3.7/site-packages/anticaptchaofficial/imagecaptcha.py", line 7, in solve_and_return_solution
    img = open(file_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'https://raw.githubusercontent.com/AdminAnticaptcha/anticaptcha-python/master/captcha.jpeg'
```

Here is a problem – https://github.com/AdminAnticaptcha/anticaptcha-python/blob/master/anticaptchaofficial/imagecaptcha.py#L7

**Comment by AdminAnticaptcha** [comment]
This function is for solving a file located on your disk. You must obviously download it first.
